micronaut:
  application:
    name: justWho
  security:
    intercept-url-map:
      -
        pattern: /search
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: /suggest
        http-method: GET
        access:
          - isAnonymous()
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
netty:
  default:
    allocator:
      max-order: 3

elasticsearch.httpHosts: https://v2202202169497180713.goodsrv.de:9200/

elasticsearch.security.user: elastic

