micronaut:
  application:
    name: justWho

netty:
  default:
    allocator:
      max-order: 3

elasticsearch.httpHosts: https://h2964346.stratoserver.net:9200/

elasticsearch.security.user: elastic

