micronaut:
  application:
    name: justWho

netty:
  default:
    allocator:
      max-order: 3

hallo:
  uri: "https://api.chucknorris.io"
  placeholder: ""
  path: "/jokes/random"

elasticsearch.httpHosts: http://85.214.64.21:9200/

elasticsearch.security.user: elastic

