PUT https://85.214.64.21:9200/movies_autosuggest
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "name": { "type": "text" },
      "year": { "type": "integer" },
      "suggest_name": { "type": "completion" }
    }
  }
}

###

### Creates new index called movies
PUT  https://85.214.64.21:9200/movies
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "name": {
        "type": "text"
      },
      "genres": {
        "type": "text"
      },
      "year": {
        "type": "integer"
      },
      "ranking": {
        "type": "integer"
      }
    }
  }
}

###
PUT https://85.214.64.21:9200/movies/_alias/movies-index