PUT {{host}}/movies_autosuggest
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "title": { "type": "text" },
      "year": { "type": "integer" },
      "suggest_title": { "type": "completion" }
    }
  }
}

###

### Creates new index called movies
PUT  {{host}}/movies
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "title": {
        "type": "text"
      },
      "overview": {
        "type": "text"
      },
      "genres": {
        "type": "text"
      },
      "release_date": {
        "type": "date"
      },
      "vote_average": {
        "type": "float"
      }
    }
  }
}

###
PUT {{host}}/movies/_alias/movies-index