### Reindex Index
POST  {{host}}/_reindex
Content-Type: application/json

{
  "source": {
    "index": "movies"
  },
  "dest": {
    "index": "movies-new"
  }
}


###
# Delete index
DELETE {{host}}/movies


###
GET http://localhost:9200/_alias
